version: '3.7'

volumes:
  crontab_data:

services:
  crontab-ui:
    build: .
    image: alseambusher/crontab-ui
    network_mode: bridge
    volumes:
      - crontab_data:/etc/crontabs
    ports:
      - 8000:8000
